In [2]:
print("shift enter")

shift enter


Here r the notes

In [3]:
2+1-3*4/5

0.6000000000000001

In [4]:
6%4

2

In [5]:
2 ** 5

32

In [6]:
1/2

0.5

In python 2 above code would have given answer as 0...

Floating point characters are never exact but a visual estimation because machine stores value in the form of binary only.

In [6]:
a=5

In [7]:
a

5

In [8]:
a=10

In [9]:
a

10

In [10]:
type(a)

int

Printing Raw strings

In [1]:
print(r'Hey Mr._\n_ew character \r\t \'_')

Hey Mr._\n_ew character \r\t \'_


Data Types

We assign a value to variable in python which determines its data type automatically

In [3]:
int n

SyntaxError: invalid syntax (<ipython-input-3-c47ce2fc38b4>, line 1)

In [35]:
int n = 10

SyntaxError: invalid syntax (<ipython-input-35-24b2f6215dfc>, line 1)

In [15]:
n=10

String (Immutable Data Type)

In [2]:
name='Haedik'

In [3]:
name[2]='r'

TypeError: 'str' object does not support item assignment

In [4]:
id(name)

2265233892552

In [5]:
name='Hardik'

In [6]:
id(name)

2265234519520

In [13]:
name[5:2:-1]

'kid'

In [1]:
a="Hard"
b="Hard"
print(id(a)==id(b))

True


In [2]:
a="Dik"
print(id(a)==id(b))
print(a)
print(b)

False
Dik
Hard


In [3]:
b="Dik"
print(id(a)==id(b))

True


---
---

Functions and Arguments

Arbitrary Arguments (No. of arguments unknown). 
1. We use * before an argument name.
    - When you call the function with many arguments, they get wrapped into a Python tuple.
    
        OR <br><br>

2. Passing Lists <br>

We iterate over both of them using For Loop.

In [1]:
def hellousrs(*names):
    for name in names:
        print("Hello, ",name)
        
hellousrs("Hardik", "HG", "H506")

Hello,  Hardik
Hello,  HG
Hello,  H506


In [2]:
def menu(food):
    for itm in food:
        print(itm)
desert = ["cake",'icecream','shakes','sweets']
menu(desert)

cake
icecream
shakes
sweets


Pass keyword - placeholder for future code.

You avoid getting an error where empty code is not allowed like in: if statements, loops, function definitions, or class definitions.

In [3]:
def func():
    pass

Recursion

In [4]:
def recursum(k):
    if(k>0):
        result = k + recursum(k-1)
    else:
        result=0
    return result
print(recursum(8))

36


Factorial using Recursion

In [5]:
def fact(n):
    if(n>1):
        result=n*fact(n-1)
    else:
        result=1
    return result
print(fact(6))

720


---

List (Mutable Data Type)

A single List can have multiple data types including lists itself. <br>
List functions: append(new_number), insert(posn, value), remove(value), pop(index_value or no_vale - LIFO), max or min or sum (list)

In [1]:
# Amazing Program Switch case in Python, used functions, dictionaries and get method, lambda func
# Took int inputs using list comprehension
# Q3. By using insert() method, pop() method, del method and extend() method.
# Make your own list to perform all these methods and print the modified list

def insert_ls():
    pos, val = int(input("Position: ")), int(input("Value: "))
    mylist.insert(pos, val)
def pop_ls():
    pos = int(input("Position: "))
    mylist.pop(pos)
def del_ls():
    start, end = int(input("Start Index: ")), int(input("End Index: "))
    del mylist[start : end]
def extend_ls():
    print("Enter values for new list")
    newlist = [int(val) for val in input().split()]
    mylist.extend(newlist)

def method(key):
    action = {
        1: insert_ls,
        2: pop_ls,
        3: del_ls,
        4: extend_ls
    }
    action.get(key, lambda: print("\nInvalid Action Key!")) ()


print("Enter space separated integers for base list: ")
mylist = [int(val) for val in input().split()]

key = int(input("Action Keys: 1.Insert 2.Pop 3.Del 4.Extend 0.Exit : "))
    
while(key):
    method(key)
    print("List: ",mylist)
    key=int(input("\nKey: "))

Enter space separated integers for base list: 
10 20 30
Action Keys: 1.Insert 2.Pop 3.Del 4.Extend 0.Exit : 1
Position: 3
Value: 40
List:  [10, 20, 30, 40]

Key: 0


In [22]:
even = [2,4,6,8,10,12,14,16,18,20]
print(min(even), " ", max(even), "\nLength: ", len(even), "\n")

del even[1:3]
print(*even)
even.pop(0)
print(*even)
even.insert(2,200)
print(*even)

odd = [1,3,5,7,9]
even.extend(odd)
print()
print(even)
even.sort()
print(even)
even.reverse()
print(even)

print("\nMississippi "," s:", "Mississippi".count('s'), "  iss:", "Mississippi".count('iss'))

2   20 
Length:  10 

2 8 10 12 14 16 18 20
8 10 12 14 16 18 20
8 10 200 12 14 16 18 20

[8, 10, 200, 12, 14, 16, 18, 20, 1, 3, 5, 7, 9]
[1, 3, 5, 7, 8, 9, 10, 12, 14, 16, 18, 20, 200]
[200, 20, 18, 16, 14, 12, 10, 9, 8, 7, 5, 3, 1]

Mississippi   s: 4   iss: 2


In [7]:
computer_parts = ["mouse","keyboard","CPU","printer"]
for part in computer_parts:
    print(part)
# or
print(computer_parts)

print(computer_parts[0:-1],"\n")

print(id(computer_parts))
computer_parts += ["monitor"]
print(id(computer_parts))

mouse
keyboard
CPU
printer
['mouse', 'keyboard', 'CPU', 'printer']
['mouse', 'keyboard', 'CPU'] 

2651498187848
2651498187848


In [5]:
l=[1,2,25]
k=[1,2,25]
print(l is k)

False


In [6]:
# Aliasing
m=l
print(l is m)
l.pop()
print(l is m)
print(l)
print(m)

True
True
[1, 2]
[1, 2]


In [7]:
# Cloning
n=l[:]
print(l is n)
print(l)
print(n)
l.append(35)
print(l)
print(n)

False
[1, 2]
[1, 2]
[1, 2, 35]
[1, 2]


In [8]:
my_list = ['cat', 'dog', 'bunny']
print('Address of my_list is: {}'.format(id(my_list)))

Address of my_list is: 1933306044360


In [10]:
my_list[0] = 'sugar glider'
print('Address of my_list is: {}'.format(id(my_list)))
print(my_list)

Address of my_list is: 1933306044360
['sugar glider', 'dog', 'bunny']


In [14]:
print(id(my_list[0]))
my_list[0] = 'rabbit'
print(id(my_list[0]))
print(id(my_list))

1933306849240
1933306849240
1933306044360


When we modify a list and change its values in place, the list keeps the same address. However, the address of the value that you changed will have a different address.

In Python Data Types
> Mutable objects:
list, dict, set
<br>
Immutable objects:
integer, float, string, tuple, bool, frozenset

Note:
>Immutability on TUPLES is only partly true. The tuple itself cannot be modified, but objects referenced by the tuple can be modified. <br> If the tuple has an immutable field like a string, then the tuple cannot be modified and it is sometimes called “non-transitive immutability.” <br> But a mutable field like a list can be edited, even if it’s embedded in the “immutable” tuple.

For a Function:
> If a mutable object is called by reference in a function, the original variable may be changed. If you want to avoid changing the original variable, you need to copy it to another variable. <br>
When immutable objects are called by reference in a function, its value cannot be changed.

In [15]:
def increment(n):
    n += 1

val = 9
increment(val)
print(val)

9


The variable val refers to the object with value 9. Python keeps an array of integer objects between -5 and 256. When you create an integer in that range, you get back a reference to the already existing object. <br>
When we pass val as a function argument to increment(n) function, the local variable n refers to the same object. However, integers are immutable so we need to create a new object with the value 10 and assign it to the variable n. <br>
The variable n is pointing to a different object from what val is pointing.

In [16]:
def assign_value(n, v):
    n = v

list1 = [1, 2, 3]
list2 = [4, 5, 6]
assign_value(list1, list2)
print(list1)

[1, 2, 3]


The variables n, v, and list2 all point to the list object [4, 5, 6], while list1 still points to the list object [1, 2, 3]. This is why when we print list1, we get the answer: [1, 2, 3]

In [17]:
def copy_list(l):
    return l[:]

my_list = [1, 2, 3]
new_list = copy_list(my_list)
print(my_list)

print(new_list)

print(my_list == new_list)

print(my_list is new_list)

print(id(my_list) == id(new_list))

[1, 2, 3]
[1, 2, 3]
True
False
False


Tuple (Non mutable Data Type)

Tuple operations: count, index, etc.

In [28]:
tup=(12,45,66,72)

In [29]:
tup[1]=21

TypeError: 'tuple' object does not support item assignment

In [31]:
tup[1]

45

Set (Mutable Data Type) (No Indexing) (Based on Hash Concept)

> Mutable: We can add or remove items from a set.

>A set is an unordered collection of items. Every set element is unique (no duplicates) and must be immutable (cannot be changed).

>Sets can also be used to perform mathematical set operations like union, intersection, symmetric difference, etc.

In [3]:
s={12,23,12,45,32,72,72,15}

In [4]:
s

{12, 15, 23, 32, 45, 72}

In [1]:
s[1]

NameError: name 's' is not defined

Mutable

In [5]:
s.add(2)

In [6]:
s

{2, 12, 15, 23, 32, 45, 72}

In [7]:
s.update([4, 5], {1, 6, 8})

In [8]:
s

{1, 2, 4, 5, 6, 8, 12, 15, 23, 32, 45, 72}

For deletion: discard()---no error and remove()---error if element not present.

In [9]:
s.remove(3)

KeyError: 3

---
---

Program 1: Input keyword

In [2]:
num1=input('First Number ')
num2=input('Second Number ')
sum = int(num1) + int(num2)
print("Sum of int =",sum)

First Number 12
Second Number 23
Sum of int = 35


Program 2: Using cmath functions

In [5]:
import cmath
num = float(input('Enter number '))
num_sqrt=cmath.sqrt(num)
print(num_sqrt)

Enter number -25
5j


Program 3: How to swap 2 variables

In [7]:
x=2
y=3
temp=x
x=y
y=temp
print("x=",x,"y=",y)

x= 3 y= 2


In [5]:
x=2
y=3
x,y=y,x # DOUBT
print("x=",x,"y=",y)

x= 3 y= 2


Above Doubt Answers:
This works for swapping because the right hand side of the "=" is evaluated first.
The way this mechanism works is a combination of two features -- forming implicit tuples and tuple/list unpacking:

>When you do something = x, y. What Python will do is implicitly create a tuple (a sort of immutable list) comprising of the two elements, x and y.

>The second feature is tuple/list unpacking. Whenever you have a series of variables on the left-hand side, and any sort of list, tuple, or other collection on the other, Python will attempt to match up each of the elements in the right to the ones on the left.

NOTE:
Remember that Python operates as a stack machine. Load_a, Load_b, and ROT_TWO.
In this case, it optimized the assignment to a ROT_TWO (i.e. swap) instruction. There's also a ROT_THREE instruction. Above 3 it works like the tuple mechanism shown at top.

Program 4: Quadratic Roots

In [8]:
import cmath

a=1
b=5
c=7

d=b**2-4*a*c

root1 = (-b+cmath.sqrt(d))/(2*a)
root2 = (-b-cmath.sqrt(d))/(2*a)

print("Roots are",root1,root2)

Roots are (-2.5+0.8660254037844386j) (-2.5-0.8660254037844386j)



Program for Armstrong Number

In [23]:
# Armstrong Number Checker => 1634 = 1^4 + 6^4 + 3^4 + 4^4
n = input("Enter your armstrong guess: ")
order = len(n)
sum = 0
n = int(n)
copy = n

while(n>0):
    digit = n%10
    sum += digit**order
    n = n//10   #FLOOR Division

if(sum==copy):
    print("Yes an Armstrong number")
else:
    print("Try again...")

Enter your armstrong guess: 1634
Yes an Armstrong number



Program 5: Adding Matrices

<br>
#### for a in ace:<br>
  * print(a)
    
#### len(mat1)

For loops take one level up (...Similarly len() takes count of one level up)
> if ace is 3d, Loop takes all 2d sheets

> if ace is 2d, Loop takes all 1d rows

> if ace is 1d, Loop takes all individual elements

In [15]:
# 3x3 Size

mat1=[[12,7,3],[4,5,6],[7,8,9]]
mat2=[[5,8,1],[6,7,3],[4,5,9]]

result1=mat1+mat2
print("Adding list directly gives",result1)

result2=[[0]*3]*3
rows, cols = (3,3)
result3=[[0 for i in range(cols)] for j in range(rows)]

print("Individual Added values")

for i in range(len(mat1)):
    for j in range(len(mat1[0])):
        result2[i][j]=mat1[i][j]+mat2[i][j]
        result3[i][j]=result2[i][j]
        print(result2[i][j])

print("Result of Shallow List ")
for r in result2:
    print(r)

print("Result using individual list objects")
for r in result3:
    print(r)

print("\nSummation of Matrix",result3)

Adding list directly gives [[12, 7, 3], [4, 5, 6], [7, 8, 9], [5, 8, 1], [6, 7, 3], [4, 5, 9]]
Individual Added values
17
15
4
10
12
9
11
13
18
Result of Shallow List 
[11, 13, 18]
[11, 13, 18]
[11, 13, 18]
Result using individual list objects
[17, 15, 4]
[10, 12, 9]
[11, 13, 18]

Summation of Matrix [[17, 15, 4], [10, 12, 9], [11, 13, 18]]


This peculiar functioning is because Python uses shallow lists
when we create a 2d array as “arr = [[0] * cols] * rows” :-
1. Only one integer object is created. (Here, integer 0)
2. A single 1d list is created and all its indices point to the same int object in point 1. ([0 -> 0, 1 -> 0, 2 -> 0])
3. Now, arr[0], arr[1], arr[2] …. arr[n-1] all point to the same list object above in point 2. 

So when 2d arrays are created like this, changing values at a certain row will effect all the rows since there is essentially only one integer object and only one list object being referenced by the all the rows of the array.

The other method creates 3 separate list objects. 

One way to check this is using the ‘is’ operator which checks if the two operands refer to the same object. See cell below.

In [16]:
print(result3[0] is result3[1]) # prints False

print(result2[0] is result2[1]) # prints True

False
True


HW Questions

Program 6: Multiply 2 matrices Program 7: Transpose of a Matrix or Assignment 1 Qs

---
---

08/02/21 : Numpy Library (Numerical Python)

NumPy is a Python library used for working with arrays.

It also has functions for working in domain of linear algebra, fourier transform, and matrices.

In [1]:
import numpy as np
arr = np.array([1,2,3])
print(arr)

[1 2 3]


array() # Create array

linspace() # Line space (start,end,no. of parts)

logspace() # Log 10 power space (start,end,no. of samples)

arange() # Similar to linespace but (start,end,gap value)

zeros() # Array of 0s (5,int)...

ones() # Array of 1s (5,int)...

In [8]:
arr = np.array([[1,2,3],[4,5,6]])
print (arr.shape)
print(arr,"\n")
arr1=arr
arr1.shape=(3,2)
print(arr1,"\n")
arr2=arr1.reshape(1,6)
print(arr2)
arr3

(2, 3)
[[1 2 3]
 [4 5 6]] 

[[1 2]
 [3 4]
 [5 6]] 

[[1 2 3 4 5 6]]


In [11]:
arr4=np.arange(24)
print(arr4,"\n")
arr5=arr4.reshape(2,4,3)
print(arr5)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23] 

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [13]:
arr=np.zeros(5,dtype=int)
print(arr)

[0 0 0 0 0]


<br>
To write Excel File xls,csv files - Library: xlwt

In [1]:
import xlwt

from xlwt import Workbook
import random

wb=Workbook()

sheet1=wb.add_sheet('Sheet1')

for i in range(50):
    n1 = random.randint(1,15)
    n2 = random.randint(1,20)
    n3 = (n1+n2)**2
    
    sheet1.write(i,0,n1)
    sheet1.write(i,1,n2)
    sheet1.write(i,2,n3)
    
wb.save('Square_Func.xls')

To manipulate big data we have to use pandas.